variables: 
  SONAR_USER_HOME:  "${CI_PROJECT_DIR}/.sonar"   # Define la ubicación del caché de la tarea de análisis 
  GIT_DEPTH:  "0"   # Le dice a git que busque todas las ramas del proyecto requeridas por la tarea de análisis 
sonarcloud-check: 
  image: 
    name:  sonarsource/sonar-scanner-cli:latest 
    entrypoint: [ "" ]
   cache: 
    key:  "${CI_JOB_NAME}" 
    paths: 
      -  .sonar/cache 
  script: 
    -  sonar-scanner 
  only: 
    -  merge_requests 
    -  master 
    -  Develop